In [2]:
import pandas as pd

In [3]:
mens_data = pd.read_csv('MenstrualCycleData.csv')

In [5]:
mens_data.head(10)

,ClientID,CycleNumber,Group,CycleWithPeakorNot,ReproductiveCategory,LengthofCycle,MeanCycleLength,EstimatedDayofOvulation,LengthofLutealPhase,FirstDayofHigh,...,Method,Prevmethod,Methoddate,Whychart,Nextpreg,NextpregM,Spousesame,SpousesameM,Timeattemptpreg,BMI
0,nfp8122,1,0,1,0,29,27.33,17,12,12,...,9,,,2,7,7,1,1,0,21.254724111867
1,nfp8122,2,0,1,0,27,,15,12,13,...,,,,,,,,,,
2,nfp8122,3,0,1,0,29,,15,14,,...,,,,,,,,,,
3,nfp8122,4,0,1,0,27,,15,12,13,...,,,,,,,,,,
4,nfp8122,5,0,1,0,28,,16,12,12,...,,,,,,,,,,
5,nfp8122,6,0,1,0,26,,15,11,10,...,,,,,,,,,,
6,nfp8122,7,0,1,0,29,,16,13,,...,,,,,,,,,,
7,nfp8122,8,0,1,2,24,,14,10,9,...,,,,,,,,,,
8,nfp8122,9,0,1,0,28,,16,12,9,...,,,,,,,,,,
9,nfp8122,10,0,1,0,28,,17,11,13,...,,,,,,,,,,

In [6]:
mens_data.describe

<bound method NDFrame.describe of      ClientID  CycleNumber  Group  CycleWithPeakorNot  ReproductiveCategory  \
0     nfp8122            1      0                   1                     0
1     nfp8122            2      0                   1                     0
2     nfp8122            3      0                   1                     0
3     nfp8122            4      0                   1                     0
4     nfp8122            5      0                   1                     0
...       ...          ...    ...                 ...                   ...
1660  nfp8334            7      1                   1                     0
1661  nfp8334            8      1                   1                     0
1662  nfp8334            9      1                   1                     0
1663  nfp8334           10      1                   1                     1
1664  nfp8334           11      1                   1                     2

      LengthofCycle MeanCycleLength EstimatedDayofOvulation  \
0                29           27.33                      17
1                27                                      15
2                29                                      15
3                27                                      15
4                28                                      16
...             ...             ...                     ...
1660             29                                      19
1661             28                                      17
1662             28                                      16
1663             40                                      27
1664             24

     LengthofLutealPhase FirstDayofHigh  ... Method Prevmethod Methoddate  \
0                     12             12  ...      9
1                     12             13  ...
2                     14                 ...
3                     12             13  ...
4                     12             12  ...
...                  ...            ...  ...    ...        ...        ...
1660                  10             13  ...
1661                  11             12  ...
1662                  12             11  ...
1663                  13             13  ...
1664                                     ...

     Whychart Nextpreg NextpregM Spousesame SpousesameM Timeattemptpreg  \
0           2        7         7          1           1               0
1
2
3
4
...       ...      ...       ...        ...         ...             ...
1660
1661
1662
1663
1664

                  BMI
0     21.254724111867
1
2
3
4
...               ...
1660
1661
1662
1663
1664

[1665 rows x 80 columns]>

In [7]:
mens_data

,ClientID,CycleNumber,Group,CycleWithPeakorNot,ReproductiveCategory,LengthofCycle,MeanCycleLength,EstimatedDayofOvulation,LengthofLutealPhase,FirstDayofHigh,...,Method,Prevmethod,Methoddate,Whychart,Nextpreg,NextpregM,Spousesame,SpousesameM,Timeattemptpreg,BMI
0,nfp8122,1,0,1,0,29,27.33,17,12,12,...,9,,,2,7,7,1,1,0,21.254724111867
1,nfp8122,2,0,1,0,27,,15,12,13,...,,,,,,,,,,
2,nfp8122,3,0,1,0,29,,15,14,,...,,,,,,,,,,
3,nfp8122,4,0,1,0,27,,15,12,13,...,,,,,,,,,,
4,nfp8122,5,0,1,0,28,,16,12,12,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1660,nfp8334,7,1,1,0,29,,19,10,13,...,,,,,,,,,,
1661,nfp8334,8,1,1,0,28,,17,11,12,...,,,,,,,,,,
1662,nfp8334,9,1,1,0,28,,16,12,11,...,,,,,,,,,,
1663,nfp8334,10,1,1,1,40,,27,13,13,...,,,,,,,,,,
1664,nfp8334,11,1,1,2,24,,,,,...,,,,,,,,,,

In [8]:
mens_data.head(5)

,ClientID,CycleNumber,Group,CycleWithPeakorNot,ReproductiveCategory,LengthofCycle,MeanCycleLength,EstimatedDayofOvulation,LengthofLutealPhase,FirstDayofHigh,...,Method,Prevmethod,Methoddate,Whychart,Nextpreg,NextpregM,Spousesame,SpousesameM,Timeattemptpreg,BMI
0,nfp8122,1,0,1,0,29,27.33,17,12,12,...,9,,,2,7,7,1,1,0,21.254724111867
1,nfp8122,2,0,1,0,27,,15,12,13,...,,,,,,,,,,
2,nfp8122,3,0,1,0,29,,15,14,,...,,,,,,,,,,
3,nfp8122,4,0,1,0,27,,15,12,13,...,,,,,,,,,,
4,nfp8122,5,0,1,0,28,,16,12,12,...,,,,,,,,,,

In [12]:
mens_data=mens_data.drop(['Group','CycleWithPeakorNot','LengthofLutealPhase','FirstDayofHigh','TotalNumberofHighDays','TotalHighPostPeak','TotalNumberofPeakDays'],axis=1)

In [17]:
mens_data.head(10)

,ClientID,CycleNumber,ReproductiveCategory,LengthofCycle,MeanCycleLength,EstimatedDayofOvulation,LengthofMenses,MeanMensesLength,MensesScoreDayOne,MensesScoreDayTwo,...,Method,Prevmethod,Methoddate,Whychart,Nextpreg,NextpregM,Spousesame,SpousesameM,Timeattemptpreg,BMI
0,nfp8122,1,0,29,27.33,17,5,4.49,3,3,...,9,,,2,7,7,1,1,0,21.254724111867
1,nfp8122,2,0,27,,15,5,,3,3,...,,,,,,,,,,
2,nfp8122,3,0,29,,15,5,,3,3,...,,,,,,,,,,
3,nfp8122,4,0,27,,15,5,,3,3,...,,,,,,,,,,
4,nfp8122,5,0,28,,16,5,,3,3,...,,,,,,,,,,
5,nfp8122,6,0,26,,15,5,,3,3,...,,,,,,,,,,
6,nfp8122,7,0,29,,16,5,,3,3,...,,,,,,,,,,
7,nfp8122,8,2,24,,14,4,,3,3,...,,,,,,,,,,
8,nfp8122,9,0,28,,16,6,,1,3,...,,,,,,,,,,
9,nfp8122,10,0,28,,17,5,,3,3,...,,,,,,,,,,

In [14]:
mens_data=mens_data.drop(['TotalDaysofFertility','TotalFertilityFormula'],axis=1)

In [16]:
mens_data=mens_data.drop(['MensesScoreDayFive','MensesScoreDaySix','MensesScoreDaySeven','MensesScoreDayEight','MensesScoreDayNine','MensesScoreDayTen','MensesScoreDay11','MensesScoreDay12','MensesScoreDay13','MensesScoreDay14','MensesScoreDay15'],axis=1)

In [19]:
column_titles = mens_data.columns.tolist()
print(column_titles)

['ClientID', 'CycleNumber', 'ReproductiveCategory', 'LengthofCycle', 'MeanCycleLength', 'EstimatedDayofOvulation', 'LengthofMenses', 'MeanMensesLength', 'MensesScoreDayOne', 'MensesScoreDayTwo', 'MensesScoreDayThree', 'MensesScoreDayFour', 'TotalMensesScore', 'MeanBleedingIntensity', 'NumberofDaysofIntercourse', 'IntercourseInFertileWindow', 'UnusualBleeding', 'PhasesBleeding', 'IntercourseDuringUnusBleed', 'Age', 'AgeM', 'Maristatus', 'MaristatusM', 'Yearsmarried', 'Wedding', 'Religion', 'ReligionM', 'Ethnicity', 'EthnicityM', 'Schoolyears', 'SchoolyearsM', 'OccupationM', 'IncomeM', 'Height', 'Weight', 'Reprocate', 'Numberpreg', 'Livingkids', 'Miscarriages', 'Abortions', 'Medvits', 'Medvitexplain', 'Gynosurgeries', 'LivingkidsM', 'Boys', 'Girls', 'MedvitsM', 'MedvitexplainM', 'Urosurgeries', 'Breastfeeding', 'Method', 'Prevmethod', 'Methoddate', 'Whychart', 'Nextpreg', 'NextpregM', 'Spousesame', 'SpousesameM', 'Timeattemptpreg', 'BMI']

In [20]:
mens_data=mens_data.drop(['TotalMensesScore', 'MeanBleedingIntensity', 'NumberofDaysofIntercourse', 'IntercourseInFertileWindow', 'PhasesBleeding', 'IntercourseDuringUnusBleed','AgeM', 'Maristatus', 'MaristatusM', 'Yearsmarried', 'Wedding', 'Religion', 'ReligionM', 'Ethnicity', 'EthnicityM', 'Schoolyears', 'SchoolyearsM', 'OccupationM', 'IncomeM','Reprocate','Livingkids', 'Miscarriages', 'Abortions', 'Medvits', 'Medvitexplain', 'Gynosurgeries', 'LivingkidsM', 'Boys', 'Girls', 'MedvitsM', 'MedvitexplainM', 'Urosurgeries', 'Breastfeeding', 'Method', 'Prevmethod', 'Methoddate', 'Whychart', 'Nextpreg', 'NextpregM', 'Spousesame', 'SpousesameM', 'Timeattemptpreg', 'BMI'],axis=1)

In [21]:
mens_data

,ClientID,CycleNumber,ReproductiveCategory,LengthofCycle,MeanCycleLength,EstimatedDayofOvulation,LengthofMenses,MeanMensesLength,MensesScoreDayOne,MensesScoreDayTwo,MensesScoreDayThree,MensesScoreDayFour,UnusualBleeding,Age,Height,Weight,Numberpreg
0,nfp8122,1,0,29,27.33,17,5,4.49,3,3,2,1,0,36,63,120,3
1,nfp8122,2,0,27,,15,5,,3,3,2,1,0,,,,
2,nfp8122,3,0,29,,15,5,,3,3,2,1,0,,,,
3,nfp8122,4,0,27,,15,5,,3,3,3,2,0,,,,
4,nfp8122,5,0,28,,16,5,,3,3,2,2,0,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1660,nfp8334,7,0,29,,19,8,,2,3,3,2,1,,,,
1661,nfp8334,8,0,28,,17,6,,3,3,2,1,0,,,,
1662,nfp8334,9,0,28,,16,5,,3,2,2,1,0,,,,
1663,nfp8334,10,1,40,,27,6,,2,3,3,2,0,,,,
1664,nfp8334,11,2,24,,,,,,,,,,,,,